### ISSUE TITLE
quality of output

### ISSUE THREAD

**Issue by sockthem** [jesvijonathan/AI-Generated-Text-Detection#1]
hi jonathan

I've tried using multiple outputs generated from chatgpt, gemini, gpt-4 . All of the results that are getting predicted are "human written" , where ideally it should come "ai generated". is there a cutoff or anything we can change? or what's the best practice to consume this?
any obersvations/insights on final output will be helpful.
![image](https://github.com/jesvijonathan/AI-Generated-Text-Detection/assets/31504279/52e0d3a8-ba3e-4805-aab1-f3a2592e9aec)

**Comment by jesvijonathan** [comment]
Hello @sockthem,
I see that there are no model visualisation graphs/results in the visualisation section. This most prolly means that model evaluation process is skipped..

Are you sure that the models are loaded and are being used ? Also check if the evaluation is one shot...

Plz provide the json (you can click on the download button in the side panel next to your Job)

Regards


![Model Eval Result Screenshot](https://github.com/jesvijonathan/AI-Generated-Text-Detection/assets/47633894/34f85003-5ed7-45ae-9087-4a3c4322c487)

**Comment by sockthem** [comment]
[job_1.json](https://github.com/jesvijonathan/AI-Generated-Text-Detection/files/14929226/job_1.json)
 
 no the models are loading i think. please find the json file attached.

**Comment by sockthem** [comment]
im still not sure why the visualisation bit is not working same as your screenshot. anything im missing?

**Comment by jesvijonathan** [comment]
Hello @sockthem,
The json you uploaded actually contains the model evaluation part too 0.69 (which is "AI generated") but it is not being used for final output... 
You can check your config.py, maybe something might be off there..
